#!/bin/bash

if [ "$(stat -c "%Y" "${CONFLUENCE_INST}/confluence/WEB-INF/classes/confluence-init.properties")" -eq "0" ]; then
  sed --in-place "s~# confluence.home=c:\/confluence\/data~confluence.home=$CONFLUENCE_HOME~" ${CONFLUENCE_INST}/confluence/WEB-INF/classes/confluence-init.properties
fi

if [ "$(stat -c "%Y" "${CONFLUENCE_INST}/conf/server.xml")" -eq "0" ]; then
  if [ -n "${TOMCAT_PROXY_NAME}" ]; then
    xmlstarlet ed --inplace --pf --ps --insert '//Connector[@port="8090"]' --type "attr" --name "proxyName" --value "${TOMCAT_PROXY_NAME}" "${CONFLUENCE_INST}/conf/server.xml"
  fi
  if [ -n "${TOMCAT_PROXY_PORT}" ]; then
    xmlstarlet ed --inplace --pf --ps --insert '//Connector[@port="8090"]' --type "attr" --name "proxyPort" --value "${TOMCAT_PROXY_PORT}" "${CONFLUENCE_INST}/conf/server.xml"
  fi
  if [ -n "${TOMCAT_PROXY_SCHEME}" ]; then
    xmlstarlet ed --inplace --pf --ps --insert '//Connector[@port="8090"]' --type "attr" --name "scheme" --value "${TOMCAT_PROXY_SCHEME}" "${CONFLUENCE_INST}/conf/server.xml"
  fi
  if [ -n "${TOMCAT_PROXY_SECURE}" ]; then
    xmlstarlet ed --inplace --pf --ps --insert '//Connector[@port="8090"]' --type "attr" --name "secure" --value "${TOMCAT_PROXY_SECURE}" "${CONFLUENCE_INST}/conf/server.xml"
  fi
  if [ -n "${TOMCAT_CONTEXT_PATH}" ]; then
    xmlstarlet ed --inplace --pf --ps --update '//Context/@path' --value "${TOMCAT_CONTEXT_PATH}" "${CONFLUENCE_INST}/conf/server.xml"
  fi
fi

if [ "$(stat -c "%Y" "${CONFLUENCE_INST}/bin/setenv.sh")" -eq "0" ]; then
  if [ -n "${JVM_MEMORY_MIN}" ]; then
    sed --in-place "s/-Xms[0-9]\{4\}m/-Xms${JVM_MEMORY_MIN}/" ${CONFLUENCE_INST}/bin/setenv.sh
  fi
  if [ -n "${JVM_MEMORY_MAX}" ]; then
    sed --in-place "s/-Xmx[0-9]\{4\}m/-Xmx${JVM_MEMORY_MAX}/" ${CONFLUENCE_INST}/bin/setenv.sh
  fi
fi

nohup ${CONFLUENCE_INST}/bin/start-confluence.sh >/dev/null 2>&1 &

/bin/bash
